stages:
  test:
    cmd: pytest training/test/ -v --tb=short && touch .test_passed
    deps:
      - training/test/
      - training/src/
    outs:
      - .test_passed:
          cache: false

  preprocess:
    cmd: python -m training.src.data.preprocess
    deps:
      - training/src/data/preprocess.py
      - data/raw
    outs:
      - data/processed:
          cache: true   # Keep in local hidden cache for performance
          push: false    # DO NOT upload these thousands of images to GDrive

  train:
    cmd: python -m training.src.model.train
    deps:
      - .test_passed
      - training/src/model/train.py
      - training/src/model/evaluate.py
      - training/src/data/preprocess.py
      - data/processed
      - training/test/
    params:
      - training/src/config/settings.py:
          - EPOCHS
          - BATCH_SIZE
          - OPTIMIZER
          - LOSS_FUNCTION
          - USE_MIXED_PRECISION
    outs:
      - models/baseline_model.h5:
          cache: true   # Cache locally
          push: false    # DO NOT upload the model weights to GDrive (Already tracked by MLflow)
      - .mlflow_run_id:
          cache: false  # Keep in Git

  validate:
    cmd: python -m training.src.model.validate --run-id $(cat .mlflow_run_id)
    deps:
      - training/src/model/validate.py
      - models/baseline_model.h5
      - .mlflow_run_id
    params:
      - training/src/config/settings.py:
          - VALIDATION_METRIC_NAME
      - common/base.py:
          - REGISTERED_MODEL_NAME